name: CI Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64"
      ANDROID_HOME: "/usr/local/lib/android/sdk"
      ANDROID_SDK_ROOT: "/usr/local/lib/android/sdk"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Decode keystore file
        run: |
           echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > app/arista-keystore.jks
           ls -la app/ 


      # Lancer les tests unitaires avant de builder l'APK
      - name: Run Unit Tests
        run: ./gradlew clean testDebugUnitTest

      # Générer le rapport de couverture Jacoco
      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport --info


      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=JumpingKeyCaps_OCR_Projet16_Exercice \
            -Dsonar.organization=jumpingkeycaps \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml  
        
        

  build:
    needs: test  # Attendre que les tests passent avant de builder l'APK
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64"
      ANDROID_HOME: "/usr/local/lib/android/sdk"
      ANDROID_SDK_ROOT: "/usr/local/lib/android/sdk"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Decode keystore file
        run: |
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > app/arista-keystore.jks
          ls -la app/ 
          

      # Construire l'APK release
      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}


      - name: Validate PR
        if: ${{ failure() }}
        run: echo "Build ou analyse de qualité échouée, PR bloquée."